2025-06-20 14:17:06,821 INFO    MainThread:81164 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-06-20 14:17:06,821 INFO    MainThread:81164 [wandb_setup.py:_flush():70] Configure stats pid to 81164
2025-06-20 14:17:06,821 INFO    MainThread:81164 [wandb_setup.py:_flush():70] Loading settings from /Users/lawrencebinding/.config/wandb/settings
2025-06-20 14:17:06,821 INFO    MainThread:81164 [wandb_setup.py:_flush():70] Loading settings from /Users/lawrencebinding/Desktop/projects/github/LDM-FDG/LDM-FDG/wandb/settings
2025-06-20 14:17:06,821 INFO    MainThread:81164 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-06-20 14:17:06,821 INFO    MainThread:81164 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /Users/lawrencebinding/Desktop/projects/github/LDM-FDG/LDM-FDG/wandb/run-20250620_141706-lblble2e/logs/debug.log
2025-06-20 14:17:06,821 INFO    MainThread:81164 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /Users/lawrencebinding/Desktop/projects/github/LDM-FDG/LDM-FDG/wandb/run-20250620_141706-lblble2e/logs/debug-internal.log
2025-06-20 14:17:06,821 INFO    MainThread:81164 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x1af1ccfd0>
2025-06-20 14:17:06,822 INFO    MainThread:81164 [wandb_init.py:init():852] calling init triggers
2025-06-20 14:17:06,822 INFO    MainThread:81164 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'learning_rate': 5e-05, 'architecture': 'Autoencoder_KL', 'dataset': 'FDG_2D_slices', 'epochs': 100, 'batch_size': 8, '_wandb': {}}
2025-06-20 14:17:06,822 INFO    MainThread:81164 [wandb_init.py:init():893] starting backend
2025-06-20 14:17:06,822 INFO    MainThread:81164 [wandb_init.py:init():897] sending inform_init request
2025-06-20 14:17:06,865 INFO    MainThread:81164 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-06-20 14:17:06,865 INFO    MainThread:81164 [wandb_init.py:init():907] backend started and connected
2025-06-20 14:17:06,873 INFO    MainThread:81164 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-06-20 14:17:06,874 INFO    MainThread:81164 [wandb_run.py:_label_probe_notebook():1386] Unable to probe notebook: Expecting value: line 1 column 1 (char 0)
2025-06-20 14:17:06,874 INFO    MainThread:81164 [wandb_init.py:init():1005] updated telemetry
2025-06-20 14:17:06,920 INFO    MainThread:81164 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-06-20 14:17:07,451 INFO    MainThread:81164 [wandb_init.py:init():1104] starting run threads in backend
2025-06-20 14:17:08,007 INFO    MainThread:81164 [wandb_run.py:_console_start():2573] atexit reg
2025-06-20 14:17:08,007 INFO    MainThread:81164 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-06-20 14:17:08,008 INFO    MainThread:81164 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-06-20 14:17:08,008 INFO    MainThread:81164 [wandb_run.py:_redirect():2513] Redirects installed.
2025-06-20 14:17:08,011 INFO    MainThread:81164 [wandb_init.py:init():1150] run started, returning control to user process
2025-06-20 14:17:09,912 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:17:32,411 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:17:32,411 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:17:38,116 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:22:14,775 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:22:14,776 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:22:14,777 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:22:34,641 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:22:34,641 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:22:43,153 WARNING MsgRouterThr:81164 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-06-20 14:22:43,173 INFO    MsgRouterThr:81164 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-06-20 14:22:43,827 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:27:40,777 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:27:40,777 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:27:40,778 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:27:40,786 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:27:45,979 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:27:45,980 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:27:45,981 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:12,360 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:28:12,360 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:28:12,361 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:12,361 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:12,474 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:28:12,478 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:12,479 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:13,783 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:28:13,783 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:28:13,784 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:13,785 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:13,839 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:28:13,839 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:13,840 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:13,913 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:28:13,914 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:28:13,914 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:13,915 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:13,969 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:28:13,970 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:13,971 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,031 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:28:14,032 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:28:14,033 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,033 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,087 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:28:14,088 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,090 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,141 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:28:14,141 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:28:14,142 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,143 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,195 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:28:14,196 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,199 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,249 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:28:14,249 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:28:14,250 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,250 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,304 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:28:14,305 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,306 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,361 INFO    MainThread:81164 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-20 14:28:14,361 INFO    MainThread:81164 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-20 14:28:14,361 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,363 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 603, in _pre_run_cell_hook
    self.backend.interface.publish_pause()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_pause
    self._publish_pause(pause)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,421 INFO    MainThread:81164 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-20 14:28:14,422 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-20 14:28:14,422 ERROR   MainThread:81164 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in _post_run_cell_hook
    self.backend.interface.publish_resume()
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 778, in publish_resume
    self._publish_resume(resume)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lawrencebinding/miniconda3/envs/ML/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
